### ISSUE TITLE
"/static/admin/img/tooltag-arrowright.png" is a gif in <1.7

### ISSUE THREAD

**Issue by mtschammer** [elky/django-flat-theme#2]
Can't use django-flat-theme atm, since the above file doesn't exist as a .png in 1.6:

```
sudo: python manage.py fasts3collectstatic --ignore *.scss --noinput
out: Copying '/usr/local/lib/python2.7/dist-packages/flat/static/admin/fonts/Roboto-Bold-webfont.woff'
out: Copying '/usr/local/lib/python2.7/dist-packages/flat/static/admin/fonts/LICENSE.txt'
out: Copying '/usr/local/lib/python2.7/dist-packages/flat/static/admin/fonts/Roboto-Light-webfont.woff'
out: Copying '/usr/local/lib/python2.7/dist-packages/flat/static/admin/fonts/Roboto-Medium-webfont.woff'
out: Copying '/usr/local/lib/python2.7/dist-packages/flat/static/admin/fonts/Roboto-Regular-webfont.woff'
out: Copying '/usr/local/lib/python2.7/dist-packages/flat/static/admin/fonts/README.txt'
out: Copying '/usr/local/lib/python2.7/dist-packages/flat/static/admin/css/base.css'
out: Copying '/usr/local/lib/python2.7/dist-packages/flat/static/admin/css/override.css'
out: Copying '/usr/local/lib/python2.7/dist-packages/flat/static/admin/css/forms.css'
out: Copying '/usr/local/lib/python2.7/dist-packages/flat/static/admin/css/fonts.css'
out: Copying '/usr/local/lib/python2.7/dist-packages/flat/static/admin/css/widgets.css'
out: Copying '/usr/local/lib/python2.7/dist-packages/flat/static/admin/css/changelists.css'
out: Copying '/usr/local/lib/python2.7/dist-packages/flat/static/admin/css/login.css'
out: Post-processed 'admin/fonts/Roboto-Bold-webfont.woff' as 'admin/fonts/Roboto-Bold-webfont.2ad99072841e.woff'
out: Post-processed 'admin/fonts/LICENSE.txt' as 'admin/fonts/LICENSE.d273d63619c9.txt'
out: Post-processed 'admin/fonts/Roboto-Light-webfont.woff' as 'admin/fonts/Roboto-Light-webfont.b446c2399bb6.woff'
out: Post-processed 'admin/fonts/Roboto-Medium-webfont.woff' as 'admin/fonts/Roboto-Medium-webfont.7c2fef29499b.woff'
out: Post-processed 'admin/fonts/Roboto-Regular-webfont.woff' as 'admin/fonts/Roboto-Regular-webfont.ec39515ae8c6.woff'
out: Post-processed 'admin/fonts/README.txt' as 'admin/fonts/README.19c10ee52bb0.txt'
out: Post-processing 'admin/css/base.css' failed!
out:
out: Traceback (most recent call last):
out:   File "manage.py", line 10, in <module>
out:     execute_from_command_line(sys.argv)
out:   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
out:     utility.execute()
out:   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
out:     self.fetch_command(subcommand).run_from_argv(self.argv)
out:   File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
out:     self.execute(*args, **options.__dict__)
out:   File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
out:     output = self.handle(*args, **options)
out:   File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 415, in handle
out:     return self.handle_noargs(**options)
out:   File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 173, in handle_noargs
out:     collected = self.collect()
out:   File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 125, in collect
out:     raise processed
out: ValueError: The file 'admin/img/tooltag-arrowright.png' could not be found with <founders_base.backends.CachedStaticS3BotoStorage object at 0x7fdd9771df90>.
out:
```

**Comment by elky** [comment]
@mtschammer should work now.

**Comment by mtschammer** [comment]
Awesome, thanks!
